site_name: SwiftPix
theme:
  name: material
  palette:
    primary: '#00A896'
    accent: '#42F57B'
  font:
    text: Roboto
    logo: assets/styleGuide/Logo.png
  language: pt-BR
  repo_url: https://github.com/SwiftPix/Docs
  repo_name: Docs
  icon:
    repo: fontawesome/brands/gitlab
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking

nav:
  - Sobre: index.md
  - Guias:
      - Guia de Commit: guide/commit_guide.md
      - Guia de Estilo: guide/style_guide.md
      - Protótipo: prototype.md
  - Comunicação:
      - Rituais da Equipe: rituals.md
      - Relatório de Eventos:
          - Semana 1: reports/week1.md
          - Semana 2: reports/week2.md
          - Semana 3: reports/week3.md
          - Semana 4: reports/week4.md
  - Planejamento:
      - Cronograma: schedule.md
      - Quadro de conhecimento: projectControl/knowledge_board.md
      - Quadro de disponibilidade: projectControl/schedule_board.md
  - Planos:
      - Plano de custos: plans/costs_plan.md
      - Plano de riscos: plans/risk_plan.md
      - Plano de testes: plans/tests_plan.md
  - Definições do Projeto:
      - Metodologias: projectDescription/index.md
      - Sebrae: projectDescription/SEBRAE.md
      - Serviços Desenvolvidos: projectDescription/developed_features.md
      - Serviços Consumidos: projectDescription/consumed_features.md
  - Gestão de Projeto:
      - EAP: projectManagment/eap.md
      - Plano de comunicação: plans/communication_plan.md
      - Backlog: projectManagment/backlog.md
      - Roadmap: projectManagment/roadmap.md
  - Lean Inception:
      - Dinâmicas: lean/dynamics.md
      - Lean: lean/index.md
  - Arquitetura:
      - Documento de arquitetura: architecture/architecture.md
      - DevOps: architecture/devops.md
  - Relatório de Encerramento do Projeto: reports/final_report.md

# Extra CSS
# extra_css:
#   - stylesheets/extra.css
